[package]
name = "robbb_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11.2", default-features = false, features = ["collector", "builder", "cache", "chrono", "client", "gateway", "model", "http", "utils"]}
poise = "0.2"
thiserror = "1.0"
sqlx = { version ="0.6", features = ["runtime-tokio-rustls", "sqlite", "chrono", "offline"] }
anyhow = "1.0"
chrono = "0.4"
itertools = "0.10"
regex = "1"
tracing = "0.1.36"
serde_json = "1"
serde = "1"
lazy_static = "1.4"
unicase = "2.6.0"
